AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Metrics - Relax for parser code
Metrics/ClassLength:
  Max: 280

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

# Allow longer blocks in tests and parser
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
